package com.yaplab.security.token;

/**
 * A Response DTO to send the response from the server to the client.
 * Only sends required information by not exposing the whole Entity.
 * @param accessToken the access token generated by the server
 */
public record AccessTokenResponseDTO(
        String accessToken
){
}
