package com.yaplab.security.token;

import com.yaplab.user.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * Repository interface to manage Groups entity.
 * Extends JPARepository to perform CRUD operations.
 */
@Repository
public interface RefreshTokenRepository extends JpaRepository<RefreshToken, Long> {

    /**
     * Finds the refresh token if available in the database by the token itself
     * @param token the refresh token generated by the server
     * @return the refresh token if found
     */
    Optional<RefreshToken> findByToken(String token);

    /**
     *
     * @param token
     * @return
     */
    Optional<RefreshToken> findByTokenAndRevokedFalse(String token);

    List<RefreshToken> findByUserAndRevokedFalse(User user);
}
